(() => {
'use strict';
const providers=[
{name:'Kamara Electricals',service:'Electrical',region:'Western Area',district:'Western Area Urban',area:'Lumley',address:'Lumley, Freetown',price:'From SLE 250',rating:'4.9',reviews:28,initials:'KE',plan:'Pro',featured:true,completed:127,completion:'98%',verified:true,desc:'Wiring, installations, repairs and troubleshooting.'},
{name:"Joe's Plumbing",service:'Plumbing',region:'Western Area',district:'Western Area Urban',area:'Aberdeen',address:'Aberdeen, Freetown',price:'From SLE 200',rating:'4.8',reviews:19,initials:'JP',plan:'Free',featured:false,completed:43,completion:'96%',verified:true,desc:'Leaks, pipes, bathroom fittings and emergency plumbing.'},
{name:'AM Tech Solutions',service:'IT & Computer',region:'Western Area',district:'Western Area Rural',area:'Hill Station',address:'Hill Station, Freetown',price:'From SLE 300',rating:'4.9',reviews:34,initials:'AT',plan:'Business',featured:true,completed:214,completion:'99%',verified:true,desc:'Computer repair, networking, software and technology support.'},
{name:'Clean Salone',service:'Cleaning',region:'Western Area',district:'Western Area Urban',area:'Central Freetown',address:'Freetown',price:'From SLE 180',rating:'4.7',reviews:16,initials:'CS',plan:'Free',featured:false,completed:31,completion:'94%',verified:false,desc:'Home, office and move-in cleaning services.'},
{name:'Mobile Doctor SL',service:'Phone Repair',region:'Western Area',district:'Western Area Urban',area:'Congo Town',address:'Congo Town, Freetown',price:'From SLE 150',rating:'4.8',reviews:22,initials:'MD',plan:'Pro',featured:false,completed:89,completion:'97%',verified:true,desc:'Screen, battery, charging-port and software repairs.'},
{name:'Bai Motors',service:'Auto Repair',region:'Southern',district:'Bo',area:'Bo Town',address:'Bo, Sierra Leone',price:'From SLE 350',rating:'4.6',reviews:13,initials:'BM',plan:'Free',featured:false,completed:27,completion:'92%',verified:false,desc:'Diagnostics, servicing, brakes and general vehicle repairs.'}
];
const categories=[['🔧','Plumbing','Leaks & pipes'],['⚡','Electrical','Wiring & installs'],['🧹','Cleaning','Home & office'],['📱','Phone Repair','Devices & screens'],['💻','IT & Computer','Tech support'],['🚗','Auto Repair','Mechanics'],['💇','Beauty','Barbers & stylists'],['🏠','Construction','Building & painting']];
const districts={'Western Area':['Western Area Urban','Western Area Rural'],'Eastern':['Kailahun','Kenema','Kono'],'Northern':['Bombali','Falaba','Koinadugu','Tonkolili'],'North West':['Kambia','Karene','Port Loko'],'Southern':['Bo','Bonthe','Moyamba','Pujehun']};
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const modal=$('modal'),body=$('modalBody');
function openModal(html){body.innerHTML=html;modal.hidden=false} function closeModal(){modal.hidden=true} window.closeModal=closeModal;
function updateDistricts(){const r=$('region').value,d=$('district'),list=districts[r]||[];d.innerHTML='<option value="">All districts</option>'+list.map(x=>'<option>'+esc(x)+'</option>').join('');d.disabled=!list.length;render()}window.updateDistricts=updateDistricts;
function render(){const q=$('search').value.trim().toLowerCase(),r=$('region').value,d=$('district').value;const list=providers.filter(p=>(!q||Object.values(p).join(' ').toLowerCase().includes(q))&&(r==='All regions'||p.region===r)&&(!d||p.district===d));$('count').textContent=list.length+' provider'+(list.length===1?'':'s')+' found';$('providerGrid').innerHTML=list.map((p,i)=>'<article class="card">'+(p.featured?'<div class="featured-badge">⭐ Featured</div>':'')+'<div class="top"><div class="avatar">'+esc(p.initials)+'</div><div><h3>'+esc(p.name)+'</h3><div class="meta">'+esc(p.service)+' · '+esc(p.region)+' · '+esc(p.district)+'</div><div class="stars">★★★★★ <span class="meta">'+p.rating+' ('+p.reviews+')</span></div></div></div><div class="price">'+esc(p.price)+'</div><div class="desc">'+esc(p.desc)+'</div><div class="meta">📍 '+esc(p.address)+'</div><div class="trust-line">'+(p.verified?'✓ Verified provider':'')+' · '+p.completed+' jobs · '+p.completion+' completion</div><div class="actions"><button class="profile-btn" data-index="'+i+'">View profile</button><button class="request-btn" data-index="'+i+'">Request</button></div></article>').join('')||'<div class="card"><h3>No providers found</h3><p class="desc">Try another service, region or district.</p></div>'}
function renderCategories(){$('categories').innerHTML=categories.map(c=>'<button class="category-btn" data-service="'+esc(c[1])+'">'+c[0]+'<b>'+esc(c[1])+'</b><small>'+esc(c[2])+'</small></button>').join('')}
function showProfile(i){const p=providers[i];openModal('<p class="eyebrow">'+esc(p.service)+'</p><h2>'+esc(p.name)+'</h2><p>★ '+p.rating+' ('+p.reviews+' reviews) · '+(p.verified?'✓ Verified':'New provider')+'</p><p>'+esc(p.desc)+'</p><div class="address-box"><b>📍 Service location</b><br>'+esc(p.address)+'<br><small>'+esc(p.region)+' · '+esc(p.district)+'</small></div><div class="stats-row"><span><b>'+p.completed+'</b><small>Jobs completed</small></span><span><b>'+p.completion+'</b><small>Completion</small></span><span><b>'+p.reviews+'</b><small>Reviews</small></span></div><p><b>Starting price:</b> '+esc(p.price)+'</p><h3>My Work</h3><p class="quote-note">Portfolio uploads will appear here when this provider adds them.</p><button class="btn" id="modalRequest">Request this provider</button>');$('modalRequest').onclick=()=>showRequest(i)}
function customerLogin(){const saved=localStorage.getItem('fixit_customer');if(saved){const u=JSON.parse(saved);openModal('<p class="eyebrow">CUSTOMER ACCOUNT</p><h2>Welcome back, '+esc(u.name)+'</h2><p>'+esc(u.phone)+'</p><button class="btn" id="continueBtn">Continue</button>');$('continueBtn').onclick=closeModal;return}openModal('<p class="eyebrow">CUSTOMER LOGIN</p><h2>Create your customer account</h2><label class="form-label">Full name</label><input id="customerName" class="form-control" placeholder="Your name"><label class="form-label">Phone number</label><input id="customerPhone" class="form-control" placeholder="+232 76 000 000"><label class="form-label">Password</label><input id="customerPassword" type="password" class="form-control" placeholder="Password"><button class="btn" id="saveCustomer">Continue</button>');$('saveCustomer').onclick=saveCustomer}window.customerLogin=customerLogin;
function saveCustomer(){const name=$('customerName').value.trim(),phone=$('customerPhone').value.trim(),pass=$('customerPassword').value;if(!name||!phone||!pass){alert('Please complete all fields.');return}localStorage.setItem('fixit_customer',JSON.stringify({name,phone}));openModal('<p class="eyebrow">ACCOUNT READY</p><h2>Welcome, '+esc(name)+'</h2><p>Your beta customer account is ready.</p><button class="btn" id="doneBtn">Continue</button>');$('doneBtn').onclick=closeModal}
function locationFields(prefix){return '<label class="form-label">Region</label><select id="'+prefix+'Region" class="form-control"><option value="">Select region</option>'+Object.keys(districts).map(r=>'<option>'+esc(r)+'</option>').join('')+'</select><label class="form-label">District</label><select id="'+prefix+'District" class="form-control" disabled><option>Select district</option></select><label class="form-label">Community / Area</label><input id="'+prefix+'Area" class="form-control" placeholder="e.g. Lumley, Aberdeen, Hill Station"><label class="form-label">Street / Landmark / Address</label><input id="'+prefix+'Address" class="form-control" placeholder="e.g. Near ..."><label class="form-label">Additional directions (optional)</label><input id="'+prefix+'Directions" class="form-control" placeholder="Helpful directions for finding the location">'}
function wireLocation(prefix){$(prefix+'Region').onchange=()=>{const r=$(prefix+'Region').value,d=$(prefix+'District'),list=districts[r]||[];d.innerHTML='<option value="">Select district</option>'+list.map(x=>'<option>'+esc(x)+'</option>').join('');d.disabled=!list.length}}
function showRequest(i){if(!localStorage.getItem('fixit_customer')){customerLogin();return}const p=providers[i];openModal('<p class="eyebrow">SERVICE REQUEST</p><h2>Request '+esc(p.service)+'</h2><p>Provider: <b>'+esc(p.name)+'</b></p>'+locationFields('request')+'<label class="form-label">Pricing type</label><select id="quoteType" class="form-control"><option>Starting price</option><option>Fixed price</option><option>Quote required</option></select><label class="form-label">Job details</label><textarea id="jobDetails" class="form-control" placeholder="Describe the work you need..."></textarea><label class="form-label">Photos (optional, up to 5)</label><input id="jobPhotos" class="form-control" type="file" accept="image/jpeg,image/png,image/webp" multiple><p class="quote-note">Final price must be approved before payment. FixIt fee: 1%.</p><button class="btn" id="submitRequest">Continue</button>');wireLocation('request');$('submitRequest').onclick=submitRequest}
function submitRequest(){const r=$('requestRegion').value,d=$('requestDistrict').value,a=$('requestArea').value.trim(),addr=$('requestAddress').value.trim(),details=$('jobDetails').value.trim(),files=$('jobPhotos').files;if(!r||!d||!a||!addr||!details){alert('Please complete your region, district, area, address and job details.');return}if(files.length>5){alert('Maximum 5 photos.');return}for(const f of files)if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>3*1024*1024){alert('Each photo must be JPG, PNG or WEBP and 3 MB or less.');return}openModal('<p class="eyebrow">REQUEST RECEIVED</p><h2>Your request is ready</h2><p>📍 '+esc(a)+', '+esc(addr)+'</p><p>'+esc(r)+' · '+esc(d)+'</p><p>The provider can review the job and send a quote for your approval.</p><button class="btn" id="closeRequest">Done</button>');$('closeRequest').onclick=closeModal}
function providerPortal(){openModal('<p class="eyebrow">PROVIDER PORTAL</p><h2>Grow your business on FixIt</h2><p>Choose a plan to unlock more customer leads and visibility.</p><div class="plan-grid"><div><b>Free</b><strong>SLE 0</strong><small>3 leads/month</small></div><div><b>Pro</b><strong>SLE 75/mo</strong><small>20 leads + portfolio</small></div><div><b>Business</b><strong>SLE 150/mo</strong><small>Priority leads + analytics</small></div></div><p class="quote-note">Featured placement can be purchased separately. Prices are beta examples and can be changed before launch.</p><button class="btn" id="profileBtn">Set up provider profile</button>');$('profileBtn').onclick=()=>providerProfile()}
function providerProfile(){openModal('<p class="eyebrow">PROVIDER PROFILE</p><h2>Your business details</h2>'+locationFields('provider')+'<label class="form-label">Business / service description</label><textarea id="providerDesc" class="form-control" placeholder="Tell customers what you do"></textarea><button class="btn" id="saveProvider">Save profile</button>');wireLocation('provider');$('saveProvider').onclick=saveProvider}
function saveProvider(){const r=$('providerRegion').value,d=$('providerDistrict').value,a=$('providerArea').value.trim(),addr=$('providerAddress').value.trim();if(!r||!d||!a||!addr){alert('Please complete region, district, area and address.');return}localStorage.setItem('fixit_provider_profile',JSON.stringify({region:r,district:d,area:a,address:addr,directions:$('providerDirections').value.trim(),description:$('providerDesc').value.trim()}));openModal('<p class="eyebrow">PROFILE SAVED</p><h2>Provider profile saved</h2><p>📍 '+esc(a)+', '+esc(addr)+'</p><button class="btn" id="profileDone">Done</button>');$('profileDone').onclick=closeModal}
function featuredListing(){openModal('<p class="eyebrow">FEATURED LISTING</p><h2>Get more visibility</h2><p>Featured providers appear prominently in relevant searches.</p><div class="plan-grid"><div><b>7 days</b><strong>SLE 25</strong><small>Featured placement</small></div><div><b>30 days</b><strong>SLE 75</strong><small>Featured placement</small></div></div><p class="quote-note">This is a beta pricing model; no payment is collected yet.</p><button class="btn" onclick="closeModal()">Got it</button>')}
function joinProvider(){providerPortal()}window.providerPortal=providerPortal;window.joinProvider=joinProvider;window.featuredListing=featuredListing;
document.addEventListener('click',e=>{const p=e.target.closest('.profile-btn'),r=e.target.closest('.request-btn'),cat=e.target.closest('.category-btn');if(p){showProfile(+p.dataset.index);return}if(r){showRequest(+r.dataset.index);return}if(cat){$('search').value=cat.dataset.service;render();$('providers').scrollIntoView({behavior:'smooth'})}});
$('search').addEventListener('input',render);$('region').addEventListener('change',updateDistricts);$('district').addEventListener('change',render);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});renderCategories();updateDistricts();
})();